// Code generated by protoc-gen-go. DO NOT EDIT.
// source: merkle.proto

package merkle

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Proof_ProofNode_Side int32

const (
	Proof_ProofNode_LEFT  Proof_ProofNode_Side = 0
	Proof_ProofNode_RIGHT Proof_ProofNode_Side = 1
)

var Proof_ProofNode_Side_name = map[int32]string{
	0: "LEFT",
	1: "RIGHT",
}

var Proof_ProofNode_Side_value = map[string]int32{
	"LEFT":  0,
	"RIGHT": 1,
}

func (x Proof_ProofNode_Side) String() string {
	return proto.EnumName(Proof_ProofNode_Side_name, int32(x))
}

func (Proof_ProofNode_Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4a45fef07aab1672, []int{2, 0, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a45fef07aab1672, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Metadata struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Parts                int32    `protobuf:"varint,2,opt,name=parts,proto3" json:"parts,omitempty"`
	ChunkSize            int32    `protobuf:"varint,3,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a45fef07aab1672, []int{1}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Metadata) GetParts() int32 {
	if m != nil {
		return m.Parts
	}
	return 0
}

func (m *Metadata) GetChunkSize() int32 {
	if m != nil {
		return m.ChunkSize
	}
	return 0
}

type Proof struct {
	Nodes                []*Proof_ProofNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	MerkleRoot           string             `protobuf:"bytes,2,opt,name=merkleRoot,proto3" json:"merkleRoot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Proof) Reset()         { *m = Proof{} }
func (m *Proof) String() string { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()    {}
func (*Proof) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a45fef07aab1672, []int{2}
}

func (m *Proof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proof.Unmarshal(m, b)
}
func (m *Proof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proof.Marshal(b, m, deterministic)
}
func (m *Proof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proof.Merge(m, src)
}
func (m *Proof) XXX_Size() int {
	return xxx_messageInfo_Proof.Size(m)
}
func (m *Proof) XXX_DiscardUnknown() {
	xxx_messageInfo_Proof.DiscardUnknown(m)
}

var xxx_messageInfo_Proof proto.InternalMessageInfo

func (m *Proof) GetNodes() []*Proof_ProofNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Proof) GetMerkleRoot() string {
	if m != nil {
		return m.MerkleRoot
	}
	return ""
}

type Proof_ProofNode struct {
	Side                 Proof_ProofNode_Side `protobuf:"varint,1,opt,name=side,proto3,enum=merkle.Proof_ProofNode_Side" json:"side,omitempty"`
	Hash                 string               `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Proof_ProofNode) Reset()         { *m = Proof_ProofNode{} }
func (m *Proof_ProofNode) String() string { return proto.CompactTextString(m) }
func (*Proof_ProofNode) ProtoMessage()    {}
func (*Proof_ProofNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a45fef07aab1672, []int{2, 0}
}

func (m *Proof_ProofNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proof_ProofNode.Unmarshal(m, b)
}
func (m *Proof_ProofNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proof_ProofNode.Marshal(b, m, deterministic)
}
func (m *Proof_ProofNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proof_ProofNode.Merge(m, src)
}
func (m *Proof_ProofNode) XXX_Size() int {
	return xxx_messageInfo_Proof_ProofNode.Size(m)
}
func (m *Proof_ProofNode) XXX_DiscardUnknown() {
	xxx_messageInfo_Proof_ProofNode.DiscardUnknown(m)
}

var xxx_messageInfo_Proof_ProofNode proto.InternalMessageInfo

func (m *Proof_ProofNode) GetSide() Proof_ProofNode_Side {
	if m != nil {
		return m.Side
	}
	return Proof_ProofNode_LEFT
}

func (m *Proof_ProofNode) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Part struct {
	Idx                  int32    `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Proof                *Proof   `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Part) Reset()         { *m = Part{} }
func (m *Part) String() string { return proto.CompactTextString(m) }
func (*Part) ProtoMessage()    {}
func (*Part) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a45fef07aab1672, []int{3}
}

func (m *Part) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Part.Unmarshal(m, b)
}
func (m *Part) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Part.Marshal(b, m, deterministic)
}
func (m *Part) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Part.Merge(m, src)
}
func (m *Part) XXX_Size() int {
	return xxx_messageInfo_Part.Size(m)
}
func (m *Part) XXX_DiscardUnknown() {
	xxx_messageInfo_Part.DiscardUnknown(m)
}

var xxx_messageInfo_Part proto.InternalMessageInfo

func (m *Part) GetIdx() int32 {
	if m != nil {
		return m.Idx
	}
	return 0
}

func (m *Part) GetProof() *Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *Part) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PartRequest struct {
	Idx                  int32    `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartRequest) Reset()         { *m = PartRequest{} }
func (m *PartRequest) String() string { return proto.CompactTextString(m) }
func (*PartRequest) ProtoMessage()    {}
func (*PartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a45fef07aab1672, []int{4}
}

func (m *PartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartRequest.Unmarshal(m, b)
}
func (m *PartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartRequest.Marshal(b, m, deterministic)
}
func (m *PartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartRequest.Merge(m, src)
}
func (m *PartRequest) XXX_Size() int {
	return xxx_messageInfo_PartRequest.Size(m)
}
func (m *PartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartRequest proto.InternalMessageInfo

func (m *PartRequest) GetIdx() int32 {
	if m != nil {
		return m.Idx
	}
	return 0
}

func init() {
	proto.RegisterEnum("merkle.Proof_ProofNode_Side", Proof_ProofNode_Side_name, Proof_ProofNode_Side_value)
	proto.RegisterType((*Empty)(nil), "merkle.Empty")
	proto.RegisterType((*Metadata)(nil), "merkle.Metadata")
	proto.RegisterType((*Proof)(nil), "merkle.Proof")
	proto.RegisterType((*Proof_ProofNode)(nil), "merkle.Proof.ProofNode")
	proto.RegisterType((*Part)(nil), "merkle.Part")
	proto.RegisterType((*PartRequest)(nil), "merkle.PartRequest")
}

func init() { proto.RegisterFile("merkle.proto", fileDescriptor_4a45fef07aab1672) }

var fileDescriptor_4a45fef07aab1672 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xa5, 0x1f, 0x5d, 0xa0, 0x53, 0x3e, 0xd3, 0x8c, 0x26, 0x36, 0x95, 0x28, 0x59, 0x2f, 0x5c,
	0x6c, 0x48, 0xfd, 0x0d, 0x88, 0x26, 0x62, 0x70, 0xe1, 0xe4, 0x6d, 0xb5, 0x4b, 0xa8, 0xd0, 0x6e,
	0x6d, 0x97, 0x44, 0xfd, 0x81, 0xfe, 0x2e, 0xd3, 0x5d, 0x28, 0x98, 0xe8, 0xa5, 0x99, 0x37, 0xf3,
	0xf6, 0xbd, 0x97, 0x99, 0x42, 0x37, 0x15, 0xc5, 0x6a, 0x2d, 0xc2, 0xbc, 0x90, 0x4a, 0x62, 0xcb,
	0x20, 0xda, 0x06, 0x32, 0x4a, 0x73, 0xf5, 0x41, 0x9f, 0xa0, 0x33, 0x11, 0x8a, 0xc7, 0x5c, 0x71,
	0x0c, 0xa0, 0xb3, 0x48, 0xd6, 0x22, 0xe3, 0xa9, 0xf0, 0xad, 0xbe, 0x35, 0x70, 0x58, 0x8d, 0xf1,
	0x04, 0x48, 0xce, 0x0b, 0x55, 0xfa, 0xff, 0xfa, 0xd6, 0x80, 0x30, 0x03, 0xb0, 0x07, 0xce, 0xcb,
	0x72, 0x93, 0xad, 0x66, 0xc9, 0xa7, 0xf0, 0x9b, 0x7a, 0xb2, 0x6f, 0xd0, 0x2f, 0x0b, 0xc8, 0xb4,
	0x90, 0x72, 0x81, 0x57, 0x40, 0x32, 0x19, 0x8b, 0xd2, 0xb7, 0xfa, 0xcd, 0x81, 0x1b, 0x9d, 0x86,
	0xdb, 0x50, 0x7a, 0x6a, 0xbe, 0x0f, 0x32, 0x16, 0xcc, 0xb0, 0xf0, 0x1c, 0xc0, 0x10, 0x98, 0x94,
	0x4a, 0x3b, 0x3a, 0xec, 0xa0, 0x13, 0x64, 0xe0, 0xd4, 0x6f, 0x70, 0x08, 0x76, 0x99, 0xc4, 0x26,
	0xf1, 0x51, 0xd4, 0xfb, 0x43, 0x3a, 0x9c, 0x25, 0xb1, 0x60, 0x9a, 0x89, 0x08, 0xf6, 0x92, 0x97,
	0xcb, 0xad, 0xb0, 0xae, 0xe9, 0x19, 0xd8, 0x15, 0x03, 0x3b, 0x60, 0xdf, 0x8f, 0x6e, 0xe6, 0x5e,
	0x03, 0x1d, 0x20, 0xec, 0x6e, 0x7c, 0x3b, 0xf7, 0x2c, 0xfa, 0x08, 0xf6, 0x94, 0x17, 0x0a, 0x3d,
	0x68, 0x26, 0xf1, 0xbb, 0x76, 0x22, 0xac, 0x2a, 0xf1, 0x12, 0x48, 0x5e, 0x59, 0x68, 0x2d, 0x37,
	0xfa, 0xff, 0xc3, 0x9d, 0x99, 0x59, 0xe5, 0x57, 0xed, 0x57, 0x2f, 0xa8, 0xcb, 0x74, 0x4d, 0x2f,
	0xc0, 0xad, 0x24, 0x99, 0x78, 0xdb, 0x88, 0xf2, 0x17, 0xe5, 0xe8, 0x15, 0x5a, 0x13, 0xad, 0x85,
	0x21, 0xb4, 0xc7, 0x42, 0xe9, 0x00, 0xc7, 0xb5, 0xfe, 0xfe, 0x6d, 0xd0, 0x3d, 0x6c, 0xd2, 0x06,
	0x0e, 0xc1, 0x1d, 0x0b, 0x55, 0x5f, 0xb5, 0xce, 0xa4, 0x0f, 0x1e, 0x78, 0x3b, 0xb8, 0x23, 0xd0,
	0xc6, 0x73, 0x4b, 0xff, 0x1c, 0xd7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x16, 0xdf, 0x9a,
	0x2c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MerkleClient is the client API for Merkle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerkleClient interface {
	GetPart(ctx context.Context, in *PartRequest, opts ...grpc.CallOption) (*Part, error)
	GetMetadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Metadata, error)
}

type merkleClient struct {
	cc *grpc.ClientConn
}

func NewMerkleClient(cc *grpc.ClientConn) MerkleClient {
	return &merkleClient{cc}
}

func (c *merkleClient) GetPart(ctx context.Context, in *PartRequest, opts ...grpc.CallOption) (*Part, error) {
	out := new(Part)
	err := c.cc.Invoke(ctx, "/merkle.Merkle/GetPart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merkleClient) GetMetadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Metadata, error) {
	out := new(Metadata)
	err := c.cc.Invoke(ctx, "/merkle.Merkle/GetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerkleServer is the server API for Merkle service.
type MerkleServer interface {
	GetPart(context.Context, *PartRequest) (*Part, error)
	GetMetadata(context.Context, *Empty) (*Metadata, error)
}

// UnimplementedMerkleServer can be embedded to have forward compatible implementations.
type UnimplementedMerkleServer struct {
}

func (*UnimplementedMerkleServer) GetPart(ctx context.Context, req *PartRequest) (*Part, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPart not implemented")
}
func (*UnimplementedMerkleServer) GetMetadata(ctx context.Context, req *Empty) (*Metadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}

func RegisterMerkleServer(s *grpc.Server, srv MerkleServer) {
	s.RegisterService(&_Merkle_serviceDesc, srv)
}

func _Merkle_GetPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerkleServer).GetPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merkle.Merkle/GetPart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerkleServer).GetPart(ctx, req.(*PartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merkle_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerkleServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merkle.Merkle/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerkleServer).GetMetadata(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Merkle_serviceDesc = grpc.ServiceDesc{
	ServiceName: "merkle.Merkle",
	HandlerType: (*MerkleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPart",
			Handler:    _Merkle_GetPart_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _Merkle_GetMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merkle.proto",
}
